spring:
  datasource:
    url: jdbc:h2:mem:terrain-db
  application:
    name: TERRAIN-SERVICE
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/auth/realms/chbaly-adil-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/auth/realms/chbaly-adil-realm/protocol/openid-connect/certs}
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'